CREATE TABLE PAUTA (
    ID                       VARCHAR NOT NULL,
    ASSUNTO                  VARCHAR NOT NULL,
    DATA_CRIACAO             TIMESTAMP     NOT NULL,

CONSTRAINT PK_PAUTA          PRIMARY KEY (ID)
);

CREATE TABLE SESSAO (
    ID                       VARCHAR NOT NULL,
    PAUTA_ID                 VARCHAR NOT NULL,
    DATA_CRIACAO             TIMESTAMP NOT NULL,
    DATA_INICIO_SESSAO       TIMESTAMP NOT NULL,
    DATA_FIM_SESSAO          TIMESTAMP NOT NULL,
    CONTAGEM_VOTOS_FAVOR     NUMERIC,
    CONTAGEM_VOTOS_CONTRA    NUMERIC,

    CONSTRAINT PK_SESSAO         PRIMARY KEY (ID),
    CONSTRAINT FK_PAUTA          FOREIGN KEY(PAUTA_ID) REFERENCES PAUTA(ID)
);

CREATE TABLE ASSOCIADO (
        ID          VARCHAR NOT NULL,
        SESSAO_ID   VARCHAR NOT NULL,
        CPF         VARCHAR(11),
        DE_VOTO     VARCHAR(3),

        CONSTRAINT PK_ASSOCIADO         PRIMARY KEY (ID),
        CONSTRAINT FK_SESSAO          FOREIGN KEY(SESSAO_ID) REFERENCES SESSAO(ID)

);