CREATE TABLE SESSAO (
    ID                       VARCHAR NOT NULL,
    PAUTA_ID                 VARCHAR NOT NULL,
    DATA_CRIACAO             TIMESTAMP NOT NULL,
    DATA_INICIO_SESSAO       TIMESTAMP NOT NULL,
    DATA_FIM_SESSAO          TIMESTAMP NOT NULL,
    CONTAGEM_VOTOS_FAVOR     NUMERIC,
    CONTAGEM_VOTOS_CONTRA    NUMERIC,

    CONSTRAINT PK_SESSAO         PRIMARY KEY (ID),
    CONSTRAINT FK_PAUTA          FOREIGN KEY(PAUTA_ID) REFERENCES PAUTA(ID)
);