version: '2'
services:

  postgres:
    image: postgres
    volumes:
      - ./scripts/db/DESAFIO_VOTACAO_DDL.sql:/docker-entrypoint-initdb.d/DESAFIO_VOTACAO_DDL.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2023!"
    ports:
      - "5432:5432"
