spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres2023!
    driver-class-name: org.postgresql.Driver